In [1]:
import pandas as pd
import numpy as np
import datetime
import pathlib

In [2]:
filename = "ML Lecture 01-meetingAttendanceList.csv"
fname = pathlib.Path(filename)
df = pd.read_csv(filename, encoding='UTF-16', sep='\t')

In [3]:
df

                       Full Name User Action              Timestamp
0              kitsuchart pasupa      Joined  1/14/2021, 1:03:57 PM
1             NATCHANON YANOTHAI      Joined  1/14/2021, 1:03:58 PM
2                THANADOL SOISON      Joined  1/14/2021, 1:03:58 PM
3             WERASUT KARNBANJOB      Joined  1/14/2021, 1:03:58 PM
4         NATTAKARN CHAIYOTMANON      Joined  1/14/2021, 1:03:58 PM
..                           ...         ...                    ...
64          APIPU RONGDEJPRATEEP      Joined  1/14/2021, 1:11:41 PM
65               CHANIN TONGJEEN      Joined  1/14/2021, 1:12:05 PM
66  TORRANIN BOONLONGSIRICHAROEN      Joined  1/14/2021, 1:12:19 PM
67            SAROCHA CHAMNANPAI      Joined  1/14/2021, 1:12:19 PM
68             SUPPHAKON LOVAKIT      Joined  1/14/2021, 1:22:17 PM

[69 rows x 3 columns]

In [4]:
df['Timestamp'] = df['Timestamp'].astype('datetime64[ns]')

In [5]:
df

                       Full Name User Action           Timestamp
0              kitsuchart pasupa      Joined 2021-01-14 13:03:57
1             NATCHANON YANOTHAI      Joined 2021-01-14 13:03:58
2                THANADOL SOISON      Joined 2021-01-14 13:03:58
3             WERASUT KARNBANJOB      Joined 2021-01-14 13:03:58
4         NATTAKARN CHAIYOTMANON      Joined 2021-01-14 13:03:58
..                           ...         ...                 ...
64          APIPU RONGDEJPRATEEP      Joined 2021-01-14 13:11:41
65               CHANIN TONGJEEN      Joined 2021-01-14 13:12:05
66  TORRANIN BOONLONGSIRICHAROEN      Joined 2021-01-14 13:12:19
67            SAROCHA CHAMNANPAI      Joined 2021-01-14 13:12:19
68             SUPPHAKON LOVAKIT      Joined 2021-01-14 13:22:17

[69 rows x 3 columns]

In [6]:
names = df['Full Name'].unique()
names

array(['kitsuchart pasupa', 'NATCHANON YANOTHAI', 'THANADOL SOISON',
       'WERASUT KARNBANJOB', 'NATTAKARN CHAIYOTMANON',
       'BENJAPORN NGERNSRITRAKUL', 'CHAYAPHOL WANANIYAKUL',
       'PHATTRAYA PURIKITIKORNKUL', 'PLOYPIM KLANGLAMYONG',
       'WAI NIRUNPORNPUTTHA', 'PATTANAYU SANGAROON', 'PUMPONG WEERAPHAN',
       'THITIRAT CHANPARASRI', 'NATCHAYA TAPASEE', 'ANU MUANGKHAM',
       'SIRINADA SUKSERM', 'KITTIPON SURUNGRUANGSAKUL', 'SUWIPA NANCHAI',
       'NUTTAWAUT AKANITSUPON', 'THANWARIN LUANGMANOTHAM',
       'BHUDITH ASSADAYUDH', 'CHANISARS PHITAKWATTANANONT',
       'SIRAPOB BOONCHAI', 'NATTAKARN KRUESANG', 'ENGFAH PUTIVARANAT',
       'PUTHANES SUWANNAKHAM', 'RACHEN KEAWNGAM', 'MASSAKORN AKSORNSIRI',
       'ROJCHANUT RODROONGRUANG', 'JUKKAPAT SRISURA',
       'KITTIKORN KITCHAROEN', 'KANOKKARN LAOPRASERTSRI',
       'WARAKORN CHERTBAMROONG', 'JITLADA LIAMPREECHA',
       'THUNYALUCK CHOTRATTANADECHDECHO', 'PREEYANUCH SUPHASUEB',
       'ANYAKAN TECHAPERASIT', 'PHUMIPHAT KLAEWKLA', 'NATEEPAN TIRUEN',
       'KATHANAT KONGPHAPA', 'PATTARAPORN LOYHAR', 'AREEYA SAMINGKAEW',
       'SIDAPORN NUMCHAN', 'PHONGSATHORN KITTIWORAPANYA',
       'NUTTAKARN SIRIPORNNO', 'NAREEKARN YUNMONGKOL',
       'SITTHISAK HORMPRATOOM', 'NAPAT JUKUL', 'KAMONCHANOK CHAROYBOON',
       'PIYATIDA SURATHUMNITI', 'NATTANAN CHAIPATCHAREEKORN',
       'NUTTAVADEE SUKTEAB', '61070283 CHANIN TONGJEEN (Guest)',
       'THANAWIN BOONTHANOM', 'KITTITHAM PHADUNGVIANG',
       'APIPU RONGDEJPRATEEP', 'CHANIN TONGJEEN',
       'TORRANIN BOONLONGSIRICHAROEN', 'SAROCHA CHAMNANPAI',
       'SUPPHAKON LOVAKIT'], dtype=object)

In [7]:
end_datetime = datetime.datetime.fromtimestamp(fname.stat().st_mtime)

In [8]:
result_dict = {
    "Full Name": [],
    "Duration": [],
    "Join Counts": [],
    "From Timestamp": [],
    "To Timestamp": []
}

for name in names:
    user_df = df[df["Full Name"] == name]
    
    last_start_time = None
    sum_time = None
    is_join = False
    join_count = 0
    
    for index, row in user_df.iterrows():
        action = row['User Action']
        timestamp = row['Timestamp']

        if action == 'Joined':
            last_start_time = timestamp
            is_join = True
            join_count += 1

        elif action == 'Left':
            is_join = False
            if not isinstance(sum_time, datetime.timedelta):
                sum_time = row['Timestamp'] - last_start_time
            else:
                sum_time += row['Timestamp'] - last_start_time

    if is_join:
        if not isinstance(sum_time, datetime.timedelta):
            sum_time = end_datetime - last_start_time
        else:
            sum_time += end_datetime - last_start_time
        to_timestamp = end_datetime
    else:
        to_timestamp = user_df['Timestamp'].iloc[-1]

    from_timestamp = user_df['Timestamp'].iloc[0]

    result_dict["Full Name"].append(user_df['Full Name'].iloc[0])
    result_dict["Duration"].append(sum_time)
    result_dict["Join Counts"].append(join_count)
    result_dict["From Timestamp"].append(from_timestamp)
    result_dict["To Timestamp"].append(to_timestamp)

In [9]:
pd.DataFrame(result_dict)

,Full Name,Duration,Join Counts,From Timestamp,To Timestamp
0,kitsuchart pasupa,00:27:59,1,2021-01-14 13:03:57,2021-01-14 13:31:56
1,NATCHANON YANOTHAI,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
2,THANADOL SOISON,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
3,WERASUT KARNBANJOB,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
4,NATTAKARN CHAIYOTMANON,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
5,BENJAPORN NGERNSRITRAKUL,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
6,CHAYAPHOL WANANIYAKUL,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
7,PHATTRAYA PURIKITIKORNKUL,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
8,PLOYPIM KLANGLAMYONG,00:25:11,2,2021-01-14 13:03:58,2021-01-14 13:31:56
9,WAI NIRUNPORNPUTTHA,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
10,PATTANAYU SANGAROON,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
11,PUMPONG WEERAPHAN,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
12,THITIRAT CHANPARASRI,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
13,NATCHAYA TAPASEE,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
14,ANU MUANGKHAM,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
15,SIRINADA SUKSERM,00:27:58,1,2021-01-14 13:03:58,2021-01-14 13:31:56
16,KITTIPON SURUNGRUANGSAKUL,00:27:55,1,2021-01-14 13:04:01,2021-01-14 13:31:56
17,SUWIPA NANCHAI,00:27:53,1,2021-01-14 13:04:03,2021-01-14 13:31:56
18,NUTTAWAUT AKANITSUPON,00:27:50,1,2021-01-14 13:04:06,2021-01-14 13:31:56
19,THANWARIN LUANGMANOTHAM,00:27:47,1,2021-01-14 13:04:09,2021-01-14 13:31:56
20,BHUDITH ASSADAYUDH,00:27:43,1,2021-01-14 13:04:13,2021-01-14 13:31:56
21,CHANISARS PHITAKWATTANANONT,00:27:41,1,2021-01-14 13:04:15,2021-01-14 13:31:56
22,SIRAPOB BOONCHAI,00:27:41,1,2021-01-14 13:04:15,2021-01-14 13:31:56
23,NATTAKARN KRUESANG,00:27:39,1,2021-01-14 13:04:17,2021-01-14 13:31:56
24,ENGFAH PUTIVARANAT,00:27:38,1,2021-01-14 13:04:18,2021-01-14 13:31:56
25,PUTHANES SUWANNAKHAM,00:27:37,1,2021-01-14 13:04:19,2021-01-14 13:31:56
26,RACHEN KEAWNGAM,00:27:35,1,2021-01-14 13:04:21,2021-01-14 13:31:56
27,MASSAKORN AKSORNSIRI,00:27:34,1,2021-01-14 13:04:22,2021-01-14 13:31:56
28,ROJCHANUT RODROONGRUANG,00:27:26,1,2021-01-14 13:04:30,2021-01-14 13:31:56
29,JUKKAPAT SRISURA,00:27:16,1,2021-01-14 13:04:40,2021-01-14 13:31:56
30,KITTIKORN KITCHAROEN,00:27:15,1,2021-01-14 13:04:41,2021-01-14 13:31:56
31,KANOKKARN LAOPRASERTSRI,00:27:13,1,2021-01-14 13:04:43,2021-01-14 13:31:56
32,WARAKORN CHERTBAMROONG,00:27:08,1,2021-01-14 13:04:48,2021-01-14 13:31:56
33,JITLADA LIAMPREECHA,00:27:08,1,2021-01-14 13:04:48,2021-01-14 13:31:56
34,THUNYALUCK CHOTRATTANADECHDECHO,00:27:07,1,2021-01-14 13:04:49,2021-01-14 13:31:56
35,PREEYANUCH SUPHASUEB,00:26:59,1,2021-01-14 13:04:57,2021-01-14 13:31:56
36,ANYAKAN TECHAPERASIT,00:26:54,1,2021-01-14 13:05:02,2021-01-14 13:31:56
37,PHUMIPHAT KLAEWKLA,00:26:49,1,2021-01-14 13:05:07,2021-01-14 13:31:56
38,NATEEPAN TIRUEN,00:25:46,2,2021-01-14 13:05:14,2021-01-14 13:31:56
39,KATHANAT KONGPHAPA,00:26:41,1,2021-01-14 13:05:15,2021-01-14 13:31:56
40,PATTARAPORN LOYHAR,00:26:27,1,2021-01-14 13:05:29,2021-01-14 13:31:56
41,AREEYA SAMINGKAEW,00:26:27,1,2021-01-14 13:05:29,2021-01-14 13:31:56
42,SIDAPORN NUMCHAN,00:26:23,1,2021-01-14 13:05:33,2021-01-14 13:31:56
43,PHONGSATHORN KITTIWORAPANYA,00:25:43,2,2021-01-14 13:05:55,2021-01-14 13:31:56
44,NUTTAKARN SIRIPORNNO,00:26:00,1,2021-01-14 13:05:56,2021-01-14 13:31:56
45,NAREEKARN YUNMONGKOL,00:25:29,1,2021-01-14 13:06:27,2021-01-14 13:31:56
46,SITTHISAK HORMPRATOOM,00:25:19,1,2021-01-14 13:06:37,2021-01-14 13:31:56
47,NAPAT JUKUL,00:21:05,2,2021-01-14 13:06:38,2021-01-14 13:31:56
48,KAMONCHANOK CHAROYBOON,00:25:12,1,2021-01-14 13:06:44,2021-01-14 13:31:56
49,PIYATIDA SURATHUMNITI,00:23:25,1,2021-01-14 13:08:31,2021-01-14 13:31:56
50,NATTANAN CHAIPATCHAREEKORN,00:23:25,1,2021-01-14 13:08:31,2021-01-14 13:31:56
51,NUTTAVADEE SUKTEAB,00:22:09,1,2021-01-14 13:09:47,2021-01-14 13:31:56
52,61070283 CHANIN TONGJEEN (Guest),00:03:14,1,2021-01-14 13:09:57,2021-01-14 13:13:11
53,THANAWIN BOONTHANOM,00:21:18,1,2021-01-14 13:10:38,2021-01-14 13:31:56
54,KITTITHAM PHADUNGVIANG,00:20:34,1,2021-01-14 13:11:22,2021-01-14 13:31:56
55,APIPU RONGDEJPRATEEP,00:20:15,1,2021-01-14 13:11:41,2021-01-14 13:31:56
56,CHANIN TONGJEEN,00:19:51,1,2021-01-14 13:12:05,2021-01-14 13:31:56
57,TORRANIN BOONLONGSIRICHAROEN,00:19:37,1,2021-01-14 13:12:19,2021-01-14 13:31:56
58,SAROCHA CHAMNANPAI,00:19:37,1,2021-01-14 13:12:19,2021-01-14 13:31:56
59,SUPPHAKON LOVAKIT,00:09:39,1,2021-01-14 13:22:17,2021-01-14 13:31:56